### ISSUE TITLE
rede-site is broken

### ISSUE THREAD

**Issue by dirceu-jr** [InfoAmazonia/rede#100]
seems that something is broken at http://rede.infoamazonia.org/
unsuccessfully tried to fix before open issue... 
<img width="1552" alt="captura de tela 2018-10-18 as 22 20 41" src="https://user-images.githubusercontent.com/20571/47192547-4386ef00-d324-11e8-9e81-456ba6d6059f.png">

**Comment by bwstefano** [comment]
Hi, @dirceup. Thanks for pinging about it. We are currently moving our hosting services and some issues will be expected for the next weeks. I'll update this topic once we finish it.

**Comment by bwstefano** [comment]
Hi @dirceup, we have fixed it. Could you please check it again?

**Comment by dirceu-jr** [comment]
Hi @bwstefano, homepage is ok now however sensor details is missing some content:
 
<img width="1440" alt="captura de tela 2018-12-19 as 06 57 54" src="https://user-images.githubusercontent.com/20571/50209664-76b52100-035b-11e9-874d-e8c72f3daff3.png">

**Comment by bwstefano** [comment]
@dirceup, could you please clarify which details are missing? Bear in mind this specific sensor of the screenshot you took last sent data to the system three months ago, while historical data at the bottom is set to show info of the last 24 hours only and the average to the left size of the screen will be of the last 30 days.

**Comment by dirceu-jr** [comment]
Then it is okay. Great project, gracefully implemented. Thank you.
