### ISSUE TITLE
Relatório 

### ISSUE THREAD

**Issue by ginaleite** [InfoAmazonia/rede#25]
Enviar texto de apresentação do relatório para Miguel (incluir antes dos gráficos)

**Comment by miguelpeixe** [comment]
incluir algorítmo que gera parâmetros a partir de outros parâmetros

**Comment by ginaleite** [comment]
O texto está disponível no link a seguir
https://docs.google.com/document/d/1KFBSM75rYe45NbF39J0-Ut9lbi23ndyuTwnvOSr9d24/edit#
