### ISSUE TITLE
links apontando para o mesmo lugar

### ISSUE THREAD

**Issue by vjpixel** [InfoAmazonia/rede#36]
na página de sensor "saiba mais" e "ver detalhes desse sensor" apontam para o mesmo lugar. faz sentido ter os 2 links?

**Comment by miguelpeixe** [comment]
compreendo que sim, 2 formas de convidar a pessoa pra página do sensor

**Comment by vjpixel** [comment]
conversei com Vitor e ele concorda comigo. achamos que o melhor é deixar o botão maior.

achamos que o "saiba mais" deve apontar para o texto sobre o IQA.

**Comment by miguelpeixe** [comment]
iqa?

**Comment by miguelpeixe** [comment]
qual botão maior?

**Comment by vjpixel** [comment]
IQA = índice de qualidade da água

botão maior = "ver detalhes desse sensor"
