### ISSUE TITLE
Cannot open sensor details because of HTTPS Everywhere

### ISSUE THREAD

**Issue by vgeorge** [InfoAmazonia/rede#43]
Error message after click on sensor details:

![captura de tela 2015-08-18 17 26 47](https://cloud.githubusercontent.com/assets/329694/9341894/111e084a-45cf-11e5-8649-57083c614154.png)

**Comment by miguelpeixe** [comment]
which environment is this?

**Comment by vgeorge** [comment]
HTTPS Everywhere is a chrome extension to enable https when it is available. 

This issue will be fixed if we enable HTTPS on our server, but this is not planned for now.
