### ISSUE TITLE
changes on the sensor page

### ISSUE THREAD

**Issue by vjpixel** [InfoAmazonia/rede#48]
in 'últimas medições'
- remove 'qualidade' column
- include 'pH' column

also:
- remove all references to 'luminância"
- remove all references to 'humidade relativa'

**Comment by miguelpeixe** [comment]
paremeters data are automatically generated from this route: http://rede.infoamazonia.org/api/v1/parameters

**Comment by miguelpeixe** [comment]
quality has been removed from the "latest readings" table, but for pH it must be removed from the backend.

**Comment by miguelpeixe** [comment]
read it wrong. i thought it was to remove the pH as parameter.

**Comment by vjpixel** [comment]
'humidade relativa' and 'luminancia' are still there.

**Comment by miguelpeixe** [comment]
thats backend
