### ISSUE TITLE
wrong time for the reading

### ISSUE THREAD

**Issue by vjpixel** [InfoAmazonia/rede#49]
apparently the readings seems to show with a timestamp 3 hours earlier.

**Comment by miguelpeixe** [comment]
This might be a backend problem.

Converting measurement id `560049f4ad07962e35ccf498`:
ISO8601 data received from API: `2015-09-21T15:18:28.000Z`
Convert to RFC 2822: `Mon, 21 Sep 2015 12:18:28 -03:00`

That's the time being displayed on the dashboard.

**Comment by miguelpeixe** [comment]
@vgeorge

**Comment by miguelpeixe** [comment]
fixed applying utc() method on momentjs
