### ISSUE TITLE
home page online shows 20 equipments

### ISSUE THREAD

**Issue by vjpixel** [InfoAmazonia/rede#56]
right now we have 29 equipments (2 prototypes), and at some moment is possible to have 24 turned on at the same time.

can you set the home page to show an unlimited list?

**Comment by miguelpeixe** [comment]
that's on the api

**Comment by vjpixel** [comment]
I still see the same problem

**Comment by vgeorge** [comment]
Because it wasn't been deployed, it's online now. 

We are not deploying after every commit, so please don't reopen issues that were solved for code available at this repo. :wink:

**Comment by vjpixel** [comment]
so I ask to please only mark as done when I can check it. we're on the
final week before presenting this site in Santarém, so I need to give you
feedback in a way that we have the site done until Tuesday.

it's ok or will break your work procedure?

On Wed, Oct 7, 2015 at 6:12 PM, Vitor George notifications@github.com
wrote:

> Because it wasn't been deployed, it's online now.
> 
> We are not deploying after every commit, so please don't reopen issues
> that were solved for code available at this repo. [image: :wink:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/InfoAmazonia/rede-site/issues/56#issuecomment-146330761
> .

## 

VJ pixel
http://twitter.com/vjpixel
http://facebook.com/vjpixel
http://memelab.culturalspot.org
http://infoamazonia.org/projects/infoamazonia-network/
