### ISSUE TITLE
Páginas institucionais

### ISSUE THREAD

**Issue by miguelpeixe** [InfoAmazonia/rede#6]

**Comment by ginaleite** [comment]
Texto em processo
https://docs.google.com/document/d/1njXwJylu-3czcSRoLHNe6_I3l7KszlvaYXtnUg3PDxk/edit

**Comment by ginaleite** [comment]
miguelpeixe

**Comment by miguelpeixe** [comment]
páginas adicionadas, aguardando finalização dos textos para atualizar conteúdo
