### ISSUE TITLE
'últimas medições' is not working

### ISSUE THREAD

**Issue by vjpixel** [InfoAmazonia/rede#68]
'últimas medições' is not working on the front page and on the sensors page.

**Comment by vgeorge** [comment]
Is this an API issue, @miguelpeixe?

**Comment by vjpixel** [comment]
![captura de pantalla de 2015-11-04 14-09-01](https://cloud.githubusercontent.com/assets/1034796/10943893/a58a6a6c-82fd-11e5-8731-0a0804ee60e1.png)

it's not showing the latest readings.

**Comment by miguelpeixe** [comment]
? your printscreen looks fine

**Comment by miguelpeixe** [comment]
latest readings is not getting the latest

**Comment by vgeorge** [comment]
Encerrando issues antigas por inatividade, reabriremos se for necessário.
