### ISSUE TITLE
npm install problem

### ISSUE THREAD

**Issue by vjpixel** [InfoAmazonia/rede#72]
when I run 'npm install' I got a error in the following command: 'napa && mkdir -p public && ./node_modules/.bin/grunt build'

**Comment by vjpixel** [comment]
fixed by changing documentation.

**Comment by vjpixel** [comment]
reopening, because the documentation is note fixed yet.

please do this ASAP, because I'm having the same problem in the server.

**Comment by vgeorge** [comment]
What is missing? Did you installed node and mongodb?

**Comment by vjpixel** [comment]
solved
