### ISSUE TITLE
zoom on map

### ISSUE THREAD

**Issue by vjpixel** [InfoAmazonia/rede#75]
I'm deploying the site in my server, and the site will just have 2 sensors, very near to each other.

when I open the site, the sensors are clustered, so I want to use more zoom in a way they're not in a cluster.

**Comment by vjpixel** [comment]
see here: http://104.236.253.150:6666/

**Comment by miguelpeixe** [comment]
since you already modified the code, looks like you are going for an independent fork, [here's where you can change the max zoom settings for the map](https://github.com/InfoAmazonia/rede-site/blob/955df4904991cb06464681a4d0a3945dbf5c27c0/src/js/controllers.js#L93)
