### ISSUE TITLE
[graph] add lines indicating max and min best values for parameters

### ISSUE THREAD

**Issue by miguelpeixe** [InfoAmazonia/rede#77]

**Comment by miguelpeixe** [comment]
need the proper values for each parameter to add as max and min best radius

**Comment by miguelpeixe** [comment]
cc @vjpixel

**Comment by vjpixel** [comment]
after a lot of discussion, I'm still unsure about this values. I propose that we keep this to another project using the platform.

**Comment by vgeorge** [comment]
Encerrando issues antigas por inatividade, reabriremos se for necessário.
