### ISSUE TITLE
indicate that deaseses are water related

### ISSUE THREAD

**Issue by miguelpeixe** [InfoAmazonia/rede#79]
On this text we need to add something that indicates that we are talking about water related deaseses:

> A Amazônia detém a maior quantidade de água doce do Brasil, 73% de toda vazão hídrica.
> Mas o acesso ao saneamento nos 771 munícipios da região está entre as piores do país.
> Na Amazônia Legal, 60% das residências são atendidas pela rede geral de água. A média nacional é de 82,7%.

**Comment by vgeorge** [comment]
Encerrando issues antigas por inatividade, reabriremos se for necessário.
