### ISSUE TITLE
include Mojuí dos Campos

### ISSUE THREAD

**Issue by vjpixel** [InfoAmazonia/rede#87]
include Mojuí dos Campos location in Viságuas

**Comment by miguelpeixe** [comment]
Mojuí dos Campos não está contemplada na pesquisa feita no VISAGUAS. Provavelmente porque quando a pesquisa foi feita ainda era considerado distrito de Santarém (se tornou município em 2013).

**Comment by miguelpeixe** [comment]
vamos colocar Mojuí dos Campos (geocode via osm) dentro de Santarém (visaguas)
