### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by miguelpeixe** [InfoAmazonia/rede#93]

**Comment by miguelpeixe** [comment]
@vjpixel needs to send me the logo files (all of them)

**Comment by vjpixel** [comment]
- GIC: https://desafiosocial.withgoogle.com/brazil2014

Realização
- InfoAmazonia

Parcerias
- Saúde e Alegria: http://www.saudeealegria.org.br/ 
- Dev Tecnologia: http://devtecnologia.com.br/

**Comment by vjpixel** [comment]
duplicated with

**Comment by vjpixel** [comment]
@miguelpeixe, the new GIC logo is on a e-mail. search for "Brasil 2".
