### ISSUE TITLE
Definição da licença

### ISSUE THREAD

**Issue by vgeorge** [InfoAmazonia/rede#99]
Há alguma definição sobre licença a ser utilizada para este código? Geralmente publico sob a [MIT](https://choosealicense.com/licenses/mit/), mas parece que alguns projetos estão começando a utilizar uma equivalente, a [ISC](https://choosealicense.com/licenses/isc/).

cc @gufalei @vjpixel

**Comment by vjpixel** [comment]
Confio em sua decisão.

**Comment by vgeorge** [comment]
Percebi agora que já havia um arquivo de licença MIT. Mantive e atualizei referências a ela no package.json e README.md.
